Noticed that the set-up for 2d_diffusion was not the actuall paper generating function. 
trying 
!conda activate ai_scientist
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Error:
/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'


pip install openai
!conda activate ai_scientist
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Error:
/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider'


Investigating what conda activate ai_scientist does...
It actives isolated environments. Since Google colab is already an isolated environment ,I will skip this command.
Also, I noticed it was trying to launch the nanoGTP_lite experiment. I changed it to 2d_diffusion
!python launch_scientist.py --model "deepseek-coder-v2-0724" --experiment nanoGPT_lite --num-ideas 2

Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider'


!pip install aider
Traceback (most recent call last):
  File "/content/AI-Scientist/launch_scientist.py", line 11, in <module>
    from aider.coders import Coder
ModuleNotFoundError: No module named 'aider.coders'


!pip install aider
from aider.coders import Coder
ModuleNotFoundError: No module named 'aider.coders'


Peculiar!!! Has the library depreciated? I'll investigate...

